name: dreamerv3-sg-test
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python~=3.8.0
  - pip~=23.1.2
  - cudatoolkit~=11.7.0
  - cudatoolkit-dev~=11.7.0
  - cudnn~=8.2.1
  - gym~=0.19.0
  - numpy<1.24,>=1.22
  - cloudpickle
  - optax
  - rich
  - ruamel.yaml
  - imageio
  - glob2
  - cmake
  - pybind11
  - click
  - matplotlib
  - joblib
  - pillow
  - plotly
  - moviepy
  - shapely
  - pyquaternion
  - sk-video
  - pip:
    - jax~=0.4.7
    - https://storage.googleapis.com/jax-releases/cuda11/jaxlib-0.4.7+cuda11.cudnn82-cp38-cp38-manylinux2014_x86_64.whl
    - tensorflow~=2.11.0
    - tensorflow-cpu~=2.11.0
    - tensorflow-probability~=0.19.0
    - crafter
    - gtimer
    - opencv-python